services:
  mysql-identity:
    image: mysql:8.0
    container_name: mysql-identity
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: identity_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_identity_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD-SHELL", "mysql -uroot -proot -e 'SELECT 1' >/dev/null 2>&1" ]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 20s

  mysql-catalog:
    image: mysql:8.0
    container_name: mysql-catalog
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: catalog_db
    ports:
      - "3308:3306"
    volumes:
      - mysql_catalog_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD-SHELL", "mysql -uroot -proot -e 'SELECT 1' >/dev/null 2>&1" ]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 20s


  identity-service:
    build:
      context: .
      dockerfile: identity-service/Dockerfile
    container_name: identity-service
    depends_on:
      mysql-identity:
        condition: service_healthy
    environment:
      SERVER_PORT: 8081
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-identity:3306/identity_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      # JWT keys are inside the jar resources via classpath by default,
      # so you usually don't need to override these.
    ports:
      - "8081:8081"

  
  catalog-service:
    build:
      context: .
      dockerfile: catalog-service/Dockerfile
    container_name: catalog-service
    depends_on:
      mysql-catalog:
        condition: service_healthy
    environment:
      SERVER_PORT: 8082
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-catalog:3308/catalog_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      # JWT keys are inside the jar resources via classpath by default,
      # so you usually don't need to override these.
    ports:
      - "8082:8082"

volumes:
  mysql_identity_data:
  mysql_catalog_data:
